require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BleatsController do

  # This should return the minimal set of attributes required to create a valid
  # Bleat. As you add validations to Bleat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BleatsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bleats as @bleats" do
      bleat = Bleat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bleats).should eq([bleat])
    end
  end

  describe "GET show" do
    it "assigns the requested bleat as @bleat" do
      bleat = Bleat.create! valid_attributes
      get :show, {:id => bleat.to_param}, valid_session
      assigns(:bleat).should eq(bleat)
    end
  end

  describe "GET new" do
    it "assigns a new bleat as @bleat" do
      get :new, {}, valid_session
      assigns(:bleat).should be_a_new(Bleat)
    end
  end

  describe "GET edit" do
    it "assigns the requested bleat as @bleat" do
      bleat = Bleat.create! valid_attributes
      get :edit, {:id => bleat.to_param}, valid_session
      assigns(:bleat).should eq(bleat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bleat" do
        expect {
          post :create, {:bleat => valid_attributes}, valid_session
        }.to change(Bleat, :count).by(1)
      end

      it "assigns a newly created bleat as @bleat" do
        post :create, {:bleat => valid_attributes}, valid_session
        assigns(:bleat).should be_a(Bleat)
        assigns(:bleat).should be_persisted
      end

      it "redirects to the created bleat" do
        post :create, {:bleat => valid_attributes}, valid_session
        response.should redirect_to(Bleat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bleat as @bleat" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bleat.any_instance.stub(:save).and_return(false)
        post :create, {:bleat => {}}, valid_session
        assigns(:bleat).should be_a_new(Bleat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bleat.any_instance.stub(:save).and_return(false)
        post :create, {:bleat => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bleat" do
        bleat = Bleat.create! valid_attributes
        # Assuming there are no other bleats in the database, this
        # specifies that the Bleat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bleat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bleat.to_param, :bleat => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bleat as @bleat" do
        bleat = Bleat.create! valid_attributes
        put :update, {:id => bleat.to_param, :bleat => valid_attributes}, valid_session
        assigns(:bleat).should eq(bleat)
      end

      it "redirects to the bleat" do
        bleat = Bleat.create! valid_attributes
        put :update, {:id => bleat.to_param, :bleat => valid_attributes}, valid_session
        response.should redirect_to(bleat)
      end
    end

    describe "with invalid params" do
      it "assigns the bleat as @bleat" do
        bleat = Bleat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bleat.any_instance.stub(:save).and_return(false)
        put :update, {:id => bleat.to_param, :bleat => {}}, valid_session
        assigns(:bleat).should eq(bleat)
      end

      it "re-renders the 'edit' template" do
        bleat = Bleat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bleat.any_instance.stub(:save).and_return(false)
        put :update, {:id => bleat.to_param, :bleat => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bleat" do
      bleat = Bleat.create! valid_attributes
      expect {
        delete :destroy, {:id => bleat.to_param}, valid_session
      }.to change(Bleat, :count).by(-1)
    end

    it "redirects to the bleats list" do
      bleat = Bleat.create! valid_attributes
      delete :destroy, {:id => bleat.to_param}, valid_session
      response.should redirect_to(bleats_url)
    end
  end

end
